struct Buffer1024 {
    sequence<octet, 1024>    payload;
    long                     length;
    long                     msg_id;
    boolean                  is_last;
};

struct Buffer1024k {
    sequence<octet, 1048576>    payload;
    long                        length;
    long                        msg_id;
    boolean                     is_last;
};

